In [2]:
from duck_solution import EngineDuck

engine = EngineDuck(host='localhost',port='5432',name='example',user='postgres',password='password')
engine.registerAllVisualizeFunctions()
engine.registerAllMlFunctions()
engine.registerAllSimilarityFunctions()

In [3]:
engine.runQuery("SELECT * FROM ml_dataset")

    id  feature1  feature2  feature3  target_regression  target_classification
0    1       2.5       3.1         1               15.2                      0
1    2       3.2       4.5         2               18.5                      1
2    3       1.8       2.9         3               12.1                      0
3    4       5.4       6.2         1               22.3                      1
4    5       4.1       5.7         2               19.8                      1
5    6       6.3       7.1         3               25.0                      0
6    7       2.9       3.6         1               14.5                      0
7    8       3.7       4.8         2               17.3                      1
8    9       5.9       6.7         3               24.1                      1
9   10       4.5       5.9         1               20.5                      0
10  11       7.1       8.3         2               27.2                      1
11  12       1.5       2.5         3               11.7                      0
12  13       6.8       7.5         1               26.8                      1
13  14       3.1       4.0         2               16.2                      0
14  15       5.2       6.0         3               21.5                      1
15  16       4.9       5.6         1               19.3                      1
16  17       2.6       3.2         2               14.8                      0
17  18       3.8       4.6         3               17.9                      1
18  19       6.1       7.2         1               25.6                      1
19  20       5.3       6.1         2               22.7                      0
20  21       2.4       3.0         3               13.5                      0
21  22       7.2       8.1         1               28.3                      1
22  23       1.9       2.8         2               12.6                      0
23  24       4.7       5.5         3               20.1                      1
24  25       6.5       7.4         1               26.0                      1
25  26       3.3       4.1         2               16.7                      0
26  27       5.6       6.3         3               23.2                      1
27  28       2.1       3.1         1               13.0                      0
28  29       4.3       5.3         2               19.0                      1
29  30       7.0       8.2         3               27.8                      1
30  31       5.1       6.2         1               22.1                      0
31  32       3.5       4.4         2               17.2                      1
32  33       6.9       7.6         3               26.5                      1
33  34       2.7       3.3         1               15.0                      0
34  35       5.8       6.5         2               23.7                      1
35  36       4.2       5.4         3               18.8                      0
36  37       3.9       4.7         1               16.3                      1
37  38       6.0       7.0         2               24.5                      1
38  39       1.7       2.6         3               11.4                      0
39  40       7.3       8.4         1               29.0                      1
40  41       4.8       5.8         2               21.3                      0
41  42       3.6       4.3         3               18.0                      1
42  43       6.4       7.3         1               25.4                      1
43  44       2.2       3.2         2               13.8                      0
44  45       5.5       6.4         3               22.5                      1
45  46       4.0       5.2         1               17.5                      1
46  47       3.0       4.2         2               15.7                      0
47  48       7.5       8.6         3               30.1                      1
48  49       1.6       2.4         1               11.0                      0
49  50       6.7       7.7         2               26.3                      1
50  51       5.0       6.1         3               20.9                      0

### Queries for ML

# KNN

WITH cteA as (SELECT feature1, feature2, feature3, target_classification FROM ml_dataset WHERE target_regression > 10 AND target_regression < 20) SELECT * from cteA)

# DECISION TREE

#

In [ ]:
engine.runQuery(""" 
WITH cteA as (SELECT feature1, feature2, feature3, target_classification FROM ml_dataset WHERE target_regression > 10 AND target_regression < 20), 
cteB AS (SELECT feature1, feature2, feature3 FROM ml_dataset WHERE target_regression < 10 OR target_regression > 20),
ml AS (SELECT CLASSIFY_KNN(3, cteB.feature1, cteB.feature2, cteB.feature3, ) FROM cteA) 
                
                SELECT * from cteB;
""")

    feature1  feature2  feature3  target_classification
0        5.4       6.2         1                      1
1        6.3       7.1         3                      0
2        5.9       6.7         3                      1
3        4.5       5.9         1                      0
4        7.1       8.3         2                      1
5        6.8       7.5         1                      1
6        5.2       6.0         3                      1
7        6.1       7.2         1                      1
8        5.3       6.1         2                      0
9        7.2       8.1         1                      1
10       4.7       5.5         3                      1
11       6.5       7.4         1                      1
12       5.6       6.3         3                      1
13       7.0       8.2         3                      1
14       5.1       6.2         1                      0
15       6.9       7.6         3                      1
16       5.8       6.5         2                      1
17       6.0       7.0         2                      1
18       7.3       8.4         1                      1
19       4.8       5.8         2                      0
20       6.4       7.3         1                      1
21       5.5       6.4         3                      1
22       7.5       8.6         3                      1
23       6.7       7.7         2                      1
24       5.0       6.1         3                      0